export const h5Configs = {
  ecommerce: {
    color: '#409eff',
    appName: '优选商城',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'category', label: '分类', icon: 'Grid' },
      { key: 'cart', label: '购物车', icon: 'ShoppingCart' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'ecommerce',
    apiResources: {
      home: 'productList',
      category: 'category',
      cart: 'orderList',
      personal: 'memberList',
    },
    searchPlaceholder: '搜索商品',
    sectionTitles: { hot: '爆款推荐', new: '新品上市' },
  },
  education: {
    color: '#67c23a',
    appName: '学在线',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'course', label: '课程', icon: 'Reading' },
      { key: 'study', label: '学习', icon: 'DataLine' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'education',
    apiResources: {
      home: 'courseList',
      course: 'courseList',
      study: 'studentList',
      personal: 'studentList',
    },
    searchPlaceholder: '搜索课程',
    sectionTitles: { hot: '热门课程', teacher: '名师推荐' },
  },
  government: {
    color: '#e6a23c',
    appName: '政务通',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'service', label: '办事', icon: 'Stamp' },
      { key: 'notice', label: '公告', icon: 'Bell' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'government',
    apiResources: {
      home: 'itemList',
      service: 'itemList',
      notice: 'policy',
      personal: 'pending',
    },
    searchPlaceholder: '搜索办事事项',
    sectionTitles: { hot: '热门事项', policy: '政策公告' },
  },
  medical: {
    color: '#f56c6c',
    appName: '健康通',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'register', label: '挂号', icon: 'FirstAidKit' },
      { key: 'record', label: '记录', icon: 'Document' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'medical',
    apiResources: {
      home: 'doctorSchedule',
      register: 'doctorSchedule',
      record: 'registration',
      personal: 'patientArchive',
    },
    searchPlaceholder: '搜索科室/医生',
    sectionTitles: { hot: '热门医生', dept: '科室导航' },
  },
  logistics: {
    color: '#909399',
    appName: '速递通',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'track', label: '查件', icon: 'Search' },
      { key: 'send', label: '寄件', icon: 'Van' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'logistics',
    apiResources: {
      home: 'waybillList',
      track: 'tracking',
      send: 'waybillList',
      personal: 'waybillList',
    },
    searchPlaceholder: '输入运单号查询',
    sectionTitles: { hot: '物流服务', track: '运单查询' },
  },
  hr: {
    color: '#b195eb',
    appName: '企务通',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'attendance', label: '考勤', icon: 'Clock' },
      { key: 'approval', label: '审批', icon: 'Stamp' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'hr',
    apiResources: {
      home: 'punchRecord',
      attendance: 'punchRecord',
      approval: 'leaveApproval',
      personal: 'employeeArchive',
    },
    searchPlaceholder: '搜索功能',
    sectionTitles: { hot: '工作台', todo: '待办事项' },
  },
  finance: {
    color: '#2f9999',
    appName: '财智通',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'reimburse', label: '报销', icon: 'Tickets' },
      { key: 'invoice', label: '发票', icon: 'Document' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'finance',
    apiResources: {
      home: 'reimburse',
      reimburse: 'reimburse',
      invoice: 'invoiceInput',
      personal: 'salaryCalc',
    },
    searchPlaceholder: '搜索报销/发票',
    sectionTitles: { hot: '快捷入口', salary: '工资查询' },
  },
  restaurant: {
    color: '#ff9f40',
    appName: '味享',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'menu', label: '商品', icon: 'Bowl' },
      { key: 'member', label: '会员', icon: 'Coin' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'restaurant',
    apiResources: {
      home: 'dishes',
      menu: 'dishes',
      member: 'memberList',
      personal: 'memberList',
    },
    searchPlaceholder: '搜索菜品',
    sectionTitles: { hot: '热销菜品', member: '会员权益' },
  },
  community: {
    color: '#00b42a',
    appName: '邻里通',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'repair', label: '报修', icon: 'SetUp' },
      { key: 'activity', label: '活动', icon: 'Calendar' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'community',
    apiResources: {
      home: 'announcement',
      repair: 'repairList',
      activity: 'publicFacility',
      personal: 'residentInfo',
    },
    searchPlaceholder: '搜索服务',
    sectionTitles: { hot: '社区服务', notice: '社区公告' },
  },
  project: {
    color: '#13c2c2',
    appName: '协作云',
    tabs: [
      { key: 'home', label: '首页', icon: 'HomeFilled' },
      { key: 'project', label: '项目', icon: 'FolderOpened' },
      { key: 'task', label: '任务', icon: 'List' },
      { key: 'personal', label: '我的', icon: 'User' },
    ],
    homeLayout: 'project',
    apiResources: {
      home: 'projects',
      project: 'projects',
      task: 'taskBoard',
      personal: 'teamMember',
    },
    searchPlaceholder: '搜索项目/任务',
    sectionTitles: { hot: '项目概览', todo: '待办任务' },
  },
};
