const userPortalConfigs = {
  ecommerce: {
    name: '优选商城',
    slogan: '品质生活，尽在优选',
    color: '#409eff',
    industryKey: 'ecommerce',
    home: {
      banners: [
        {
          title: '新年大促',
          subtitle: '全场满300减50',
          bg: 'linear-gradient(135deg, #409eff, #667eea)',
        },
        {
          title: '新品首发',
          subtitle: 'iPhone 15 Pro 火热预售',
          bg: 'linear-gradient(135deg, #667eea, #764ba2)',
        },
        {
          title: '会员专享',
          subtitle: '钻石会员8折起',
          bg: 'linear-gradient(135deg, #f093fb, #f5576c)',
        },
      ],
      categories: [
        { name: '手机数码', icon: '📱' },
        { name: '电脑办公', icon: '💻' },
        { name: '家用电器', icon: '🏠' },
        { name: '服饰鞋包', icon: '👔' },
        { name: '美妆护肤', icon: '💄' },
        { name: '食品生鲜', icon: '🍎' },
        { name: '图书文具', icon: '📚' },
        { name: '运动户外', icon: '⚽' },
      ],
      hotProducts: [
        {
          name: 'iPhone 15 Pro',
          price: '¥8,999',
          originalPrice: '¥9,999',
          img: '📱',
          sales: '2.3万',
          tag: '爆款',
        },
        {
          name: 'MacBook Air M3',
          price: '¥9,499',
          originalPrice: '¥10,999',
          img: '💻',
          sales: '1.5万',
          tag: '新品',
        },
        {
          name: 'AirPods Pro 2',
          price: '¥1,899',
          originalPrice: '¥1,999',
          img: '🎧',
          sales: '5.6万',
          tag: '',
        },
        {
          name: 'iPad Mini 6',
          price: '¥3,799',
          originalPrice: '¥3,999',
          img: '📟',
          sales: '8,900',
          tag: '',
        },
        {
          name: 'Apple Watch S9',
          price: '¥2,999',
          originalPrice: '¥3,199',
          img: '⌚',
          sales: '3.2万',
          tag: '热卖',
        },
        {
          name: 'HomePod Mini',
          price: '¥749',
          originalPrice: '¥799',
          img: '🔊',
          sales: '1.1万',
          tag: '',
        },
      ],
    },
    business: {
      listTitle: '全部商品',
      filters: ['全部', '手机数码', '电脑办公', '家用电器', '服饰鞋包', '美妆护肤'],
      sortOptions: ['综合排序', '价格从低到高', '价格从高到低', '销量优先'],
      products: [
        {
          name: 'iPhone 15 Pro Max 256GB',
          price: '¥9,999',
          img: '📱',
          sales: '1.2万',
          rating: 4.9,
          specs: ['256GB', '512GB', '1TB'],
          colors: ['原色', '蓝色', '白色', '黑色'],
        },
        {
          name: 'MacBook Pro 14英寸 M3',
          price: '¥14,999',
          img: '💻',
          sales: '8,600',
          rating: 4.8,
          specs: ['16GB+512GB', '32GB+1TB'],
          colors: ['深空灰', '银色'],
        },
        {
          name: 'AirPods Max',
          price: '¥4,399',
          img: '🎧',
          sales: '3.5万',
          rating: 4.7,
          specs: ['标准版'],
          colors: ['银色', '深空灰', '粉色', '绿色', '蓝色'],
        },
        {
          name: 'iPad Air 5',
          price: '¥4,799',
          img: '📟',
          sales: '6,200',
          rating: 4.8,
          specs: ['64GB', '256GB'],
          colors: ['深空灰', '银色', '粉色', '紫色', '蓝色'],
        },
      ],
      detailProduct: {
        name: 'iPhone 15 Pro',
        price: '¥8,999',
        originalPrice: '¥9,999',
        sales: '2.3万',
        rating: 4.9,
        description: '全新A17 Pro芯片，钛金属设计，4800万像素主摄，支持USB-C，全天候续航。',
        features: [
          'A17 Pro芯片',
          '钛金属边框',
          '4800万主摄',
          'USB-C接口',
          '全天候显示',
          'IP68防水',
        ],
        images: ['📱', '📲', '📞'],
      },
    },
    personal: {
      userName: '张三',
      userAvatar: '👨',
      userLevel: '钻石会员',
      menus: [
        { label: '我的订单', icon: 'List', count: 12 },
        { label: '收货地址', icon: 'Location', count: 3 },
        { label: '我的收藏', icon: 'Star', count: 28 },
        { label: '账户设置', icon: 'Setting', count: 0 },
      ],
      orders: [
        {
          id: 'ORD20260101',
          product: 'iPhone 15 Pro',
          amount: '¥8,999',
          status: '已发货',
          date: '2026-01-15',
        },
        {
          id: 'ORD20260102',
          product: 'MacBook Air',
          amount: '¥9,499',
          status: '待发货',
          date: '2026-01-16',
        },
        {
          id: 'ORD20260103',
          product: 'AirPods Pro',
          amount: '¥1,899',
          status: '已完成',
          date: '2026-01-17',
        },
        {
          id: 'ORD20260104',
          product: 'iPad Mini',
          amount: '¥3,799',
          status: '已取消',
          date: '2026-01-18',
        },
      ],
    },
  },

  education: {
    name: '学在线',
    slogan: '知识改变命运，学习成就未来',
    color: '#67c23a',
    industryKey: 'education',
    home: {
      banners: [
        {
          title: '春季课程上新',
          subtitle: '全场课程8折起',
          bg: 'linear-gradient(135deg, #67c23a, #43e97b)',
        },
        {
          title: '名师直播',
          subtitle: '每晚8点，名师在线答疑',
          bg: 'linear-gradient(135deg, #43e97b, #38f9d7)',
        },
        {
          title: '学习打卡',
          subtitle: '连续打卡赢积分',
          bg: 'linear-gradient(135deg, #a8edea, #fed6e3)',
        },
      ],
      categories: [
        { name: '前端开发', icon: '💻' },
        { name: '后端开发', icon: '⚙️' },
        { name: '人工智能', icon: '🤖' },
        { name: '产品设计', icon: '🎨' },
        { name: '数据分析', icon: '📊' },
        { name: '外语学习', icon: '🌍' },
        { name: '职业考试', icon: '📝' },
        { name: '兴趣生活', icon: '🎵' },
      ],
      hotProducts: [
        {
          name: 'Vue3全栈开发实战',
          price: '¥199',
          originalPrice: '¥399',
          img: '📘',
          sales: '1.2万',
          tag: '爆款',
        },
        {
          name: 'Python数据分析入门',
          price: '¥149',
          originalPrice: '¥299',
          img: '📗',
          sales: '8,600',
          tag: '新课',
        },
        {
          name: 'React进阶实战指南',
          price: '¥179',
          originalPrice: '¥359',
          img: '📕',
          sales: '5,300',
          tag: '',
        },
        {
          name: 'Node.js微服务架构',
          price: '¥169',
          originalPrice: '¥339',
          img: '📙',
          sales: '3,200',
          tag: '',
        },
        {
          name: 'AI大模型应用开发',
          price: '¥249',
          originalPrice: '¥499',
          img: '🤖',
          sales: '2.1万',
          tag: '热门',
        },
        {
          name: 'UI设计从入门到精通',
          price: '¥129',
          originalPrice: '¥259',
          img: '🎨',
          sales: '4,500',
          tag: '',
        },
      ],
    },
    business: {
      listTitle: '全部课程',
      filters: ['全部', '免费课程', '付费课程', '直播课', '录播课'],
      sortOptions: ['综合排序', '最新上架', '销量优先', '价格从低到高'],
      products: [
        {
          name: 'Vue3全栈开发实战',
          price: '¥199',
          img: '📘',
          sales: '1.2万',
          rating: 4.9,
          specs: ['64课时', '128课时'],
          colors: ['基础班', '进阶班'],
        },
        {
          name: 'Python数据分析',
          price: '¥149',
          img: '📗',
          sales: '8,600',
          rating: 4.8,
          specs: ['48课时'],
          colors: ['标准版'],
        },
        {
          name: 'React进阶实战',
          price: '¥179',
          img: '📕',
          sales: '5,300',
          rating: 4.7,
          specs: ['64课时'],
          colors: ['标准版'],
        },
        {
          name: 'AI大模型开发',
          price: '¥249',
          img: '🤖',
          sales: '2.1万',
          rating: 4.9,
          specs: ['96课时'],
          colors: ['基础班', '项目班'],
        },
      ],
      detailProduct: {
        name: 'Vue3全栈开发实战',
        price: '¥199',
        originalPrice: '¥399',
        sales: '1.2万',
        rating: 4.9,
        description:
          '从零到一掌握Vue3全家桶，包含Composition API、Pinia、Vue Router、TypeScript等核心技术，实战项目驱动教学。',
        features: [
          'Composition API',
          'Pinia状态管理',
          'Vue Router路由',
          'TypeScript集成',
          '项目实战',
          '源码解析',
        ],
        images: ['📘', '📖', '📚'],
      },
    },
    personal: {
      userName: '张小明',
      userAvatar: '👨‍🎓',
      userLevel: '高级学员',
      menus: [
        { label: '我的课程', icon: 'Reading', count: 5 },
        { label: '学习进度', icon: 'DataLine', count: 0 },
        { label: '我的订单', icon: 'List', count: 8 },
        { label: '证书中心', icon: 'Medal', count: 3 },
      ],
      orders: [
        {
          id: 'C20260001',
          product: 'Vue3全栈开发',
          amount: '¥199',
          status: '学习中',
          date: '2026-01-10',
        },
        {
          id: 'C20260002',
          product: 'Python数据分析',
          amount: '¥149',
          status: '已完成',
          date: '2025-12-20',
        },
        {
          id: 'C20260003',
          product: 'AI大模型开发',
          amount: '¥249',
          status: '未开始',
          date: '2026-01-18',
        },
      ],
    },
  },

  government: {
    name: '政务通',
    slogan: '让群众少跑腿，让数据多跑路',
    color: '#e6a23c',
    industryKey: 'government',
    home: {
      banners: [
        {
          title: '一网通办',
          subtitle: '足不出户办理各类事项',
          bg: 'linear-gradient(135deg, #e6a23c, #f5c842)',
        },
        {
          title: '政策发布',
          subtitle: '最新政策第一时间了解',
          bg: 'linear-gradient(135deg, #f5c842, #f0d78c)',
        },
        {
          title: '便民服务',
          subtitle: '社保公积金在线查询',
          bg: 'linear-gradient(135deg, #ffecd2, #fcb69f)',
        },
      ],
      categories: [
        { name: '社保服务', icon: '🛡️' },
        { name: '户政办理', icon: '🏠' },
        { name: '工商注册', icon: '🏢' },
        { name: '税务服务', icon: '💰' },
        { name: '公积金', icon: '🏦' },
        { name: '交通出行', icon: '🚗' },
        { name: '医疗卫生', icon: '🏥' },
        { name: '教育服务', icon: '🎓' },
      ],
      hotProducts: [
        { name: '营业执照申请', price: '免费', img: '📋', sales: '5.6万', tag: '热门' },
        { name: '户口迁移办理', price: '免费', img: '📄', sales: '3.2万', tag: '' },
        { name: '社保转移接续', price: '免费', img: '🛡️', sales: '2.8万', tag: '' },
        { name: '居住证办理', price: '免费', img: '🪪', sales: '4.1万', tag: '常用' },
        { name: '公积金提取', price: '免费', img: '🏦', sales: '6.3万', tag: '热门' },
        { name: '不动产登记', price: '免费', img: '🏠', sales: '1.9万', tag: '' },
      ],
    },
    business: {
      listTitle: '办事事项',
      filters: ['全部', '社保服务', '户政办理', '工商注册', '税务服务'],
      sortOptions: ['默认排序', '办理量最多', '办理时限最短'],
      products: [
        {
          name: '营业执照申请',
          price: '免费',
          img: '📋',
          sales: '5.6万',
          rating: 4.8,
          specs: ['5工作日'],
          colors: ['新办', '变更'],
        },
        {
          name: '户口迁移办理',
          price: '免费',
          img: '📄',
          sales: '3.2万',
          rating: 4.6,
          specs: ['3工作日'],
          colors: ['市内迁移', '跨市迁移'],
        },
        {
          name: '社保转移接续',
          price: '免费',
          img: '🛡️',
          sales: '2.8万',
          rating: 4.5,
          specs: ['7工作日'],
          colors: ['省内转移', '跨省转移'],
        },
        {
          name: '居住证办理',
          price: '免费',
          img: '🪪',
          sales: '4.1万',
          rating: 4.7,
          specs: ['5工作日'],
          colors: ['新办', '续签'],
        },
      ],
      detailProduct: {
        name: '营业执照申请',
        price: '免费',
        originalPrice: '',
        sales: '5.6万',
        rating: 4.8,
        description:
          '在线申请营业执照，无需跑腿，全程电子化办理。支持新办、变更、注销等多种业务类型。',
        features: ['在线申请', '电子签章', '快递送达', '进度查询', '材料预审', '智能填单'],
        images: ['📋', '📑', '🗂️'],
      },
    },
    personal: {
      userName: '张先生',
      userAvatar: '👨‍💼',
      userLevel: '已认证市民',
      menus: [
        { label: '我的办件', icon: 'Document', count: 5 },
        { label: '我的收藏', icon: 'Star', count: 12 },
        { label: '个人信息', icon: 'User', count: 0 },
        { label: '意见反馈', icon: 'ChatDotRound', count: 0 },
      ],
      orders: [
        {
          id: 'GV20260101',
          product: '营业执照申请',
          amount: '免费',
          status: '办理中',
          date: '2026-01-20',
        },
        {
          id: 'GV20260102',
          product: '户口迁移',
          amount: '免费',
          status: '已办结',
          date: '2026-01-15',
        },
        {
          id: 'GV20260103',
          product: '社保转移',
          amount: '免费',
          status: '待提交',
          date: '2026-01-22',
        },
      ],
    },
  },

  medical: {
    name: '健康通',
    slogan: '智慧医疗，健康生活',
    color: '#f56c6c',
    industryKey: 'medical',
    home: {
      banners: [
        {
          title: '在线挂号',
          subtitle: '三甲医院专家号源',
          bg: 'linear-gradient(135deg, #f56c6c, #ff8a80)',
        },
        {
          title: '健康体检',
          subtitle: '体检套餐限时优惠',
          bg: 'linear-gradient(135deg, #ff8a80, #ffcdd2)',
        },
        {
          title: '用药指导',
          subtitle: '专业药师在线咨询',
          bg: 'linear-gradient(135deg, #ffcdd2, #fce4ec)',
        },
      ],
      categories: [
        { name: '内科', icon: '🫀' },
        { name: '外科', icon: '🦴' },
        { name: '儿科', icon: '👶' },
        { name: '妇科', icon: '👩‍⚕️' },
        { name: '眼科', icon: '👁️' },
        { name: '口腔科', icon: '🦷' },
        { name: '中医科', icon: '🌿' },
        { name: '皮肤科', icon: '🧴' },
      ],
      hotProducts: [
        { name: '王主任 · 内科', price: '¥50起', img: '👨‍⚕️', sales: '3.2万', tag: '推荐' },
        { name: '李医生 · 外科', price: '¥60起', img: '👨‍⚕️', sales: '2.1万', tag: '' },
        { name: '赵医生 · 儿科', price: '¥45起', img: '👩‍⚕️', sales: '4.5万', tag: '热门' },
        { name: '刘主任 · 眼科', price: '¥55起', img: '👨‍⚕️', sales: '1.8万', tag: '' },
        { name: '陈医生 · 中医科', price: '¥40起', img: '👩‍⚕️', sales: '2.6万', tag: '' },
        { name: '周医生 · 口腔科', price: '¥80起', img: '👨‍⚕️', sales: '3.8万', tag: '好评' },
      ],
    },
    business: {
      listTitle: '预约挂号',
      filters: ['全部', '内科', '外科', '儿科', '妇科', '眼科', '口腔科', '中医科'],
      sortOptions: ['默认排序', '评分最高', '号源最多'],
      products: [
        {
          name: '王主任 · 心内科',
          price: '¥50',
          img: '👨‍⚕️',
          sales: '3.2万',
          rating: 4.9,
          specs: ['上午', '下午'],
          colors: ['周一', '周三', '周四'],
        },
        {
          name: '李医生 · 骨科',
          price: '¥60',
          img: '👨‍⚕️',
          sales: '2.1万',
          rating: 4.7,
          specs: ['全天'],
          colors: ['周二', '周三', '周五'],
        },
        {
          name: '赵医生 · 儿科',
          price: '¥45',
          img: '👩‍⚕️',
          sales: '4.5万',
          rating: 4.8,
          specs: ['上午', '下午'],
          colors: ['周一', '周二', '周四'],
        },
        {
          name: '陈医生 · 中医科',
          price: '¥40',
          img: '👩‍⚕️',
          sales: '2.6万',
          rating: 4.9,
          specs: ['全天'],
          colors: ['周一至周五'],
        },
      ],
      detailProduct: {
        name: '王主任 · 心内科',
        price: '¥50',
        originalPrice: '¥80',
        sales: '3.2万',
        rating: 4.9,
        description: '主任医师，从医30年，擅长冠心病、高血压、心律失常等心血管疾病的诊治。',
        features: ['主任医师', '30年经验', '在线问诊', '电子处方', '报告查询', '复诊提醒'],
        images: ['👨‍⚕️', '🏥', '💊'],
      },
    },
    personal: {
      userName: '张三',
      userAvatar: '👨',
      userLevel: '健康会员',
      menus: [
        { label: '我的预约', icon: 'Calendar', count: 2 },
        { label: '就诊记录', icon: 'Document', count: 15 },
        { label: '我的处方', icon: 'FirstAidKit', count: 8 },
        { label: '健康档案', icon: 'Notebook', count: 0 },
      ],
      orders: [
        {
          id: 'RG20260101',
          product: '心内科 · 王主任',
          amount: '¥50',
          status: '已预约',
          date: '2026-01-25',
        },
        {
          id: 'RG20260102',
          product: '骨科 · 李医生',
          amount: '¥60',
          status: '已就诊',
          date: '2026-01-20',
        },
        {
          id: 'RG20260103',
          product: '儿科 · 赵医生',
          amount: '¥45',
          status: '候诊中',
          date: '2026-01-22',
        },
      ],
    },
  },

  logistics: {
    name: '速递通',
    slogan: '寄件查件，一键搞定',
    color: '#909399',
    industryKey: 'logistics',
    home: {
      banners: [
        {
          title: '寄件优惠',
          subtitle: '首单立减10元',
          bg: 'linear-gradient(135deg, #909399, #b1b3b8)',
        },
        {
          title: '实时追踪',
          subtitle: '包裹动态随时查',
          bg: 'linear-gradient(135deg, #b1b3b8, #c0c4cc)',
        },
        {
          title: '网点查询',
          subtitle: '附近网点一键导航',
          bg: 'linear-gradient(135deg, #c0c4cc, #d3d4d6)',
        },
      ],
      categories: [
        { name: '我要寄件', icon: '📦' },
        { name: '运单查询', icon: '🔍' },
        { name: '网点查询', icon: '📍' },
        { name: '时效查询', icon: '⏰' },
        { name: '运费估算', icon: '💰' },
        { name: '包裹代收', icon: '📬' },
        { name: '国际物流', icon: '✈️' },
        { name: '大件物流', icon: '🚛' },
      ],
      hotProducts: [
        { name: '标准快递', price: '¥12起', img: '📦', sales: '10万+', tag: '常用' },
        { name: '特快专递', price: '¥25起', img: '🚀', sales: '5.6万', tag: '极速' },
        { name: '冷链运输', price: '¥35起', img: '❄️', sales: '2.3万', tag: '' },
        { name: '大件物流', price: '¥50起', img: '🚛', sales: '1.8万', tag: '' },
        { name: '国际快递', price: '¥80起', img: '✈️', sales: '3.2万', tag: '' },
        { name: '同城急送', price: '¥15起', img: '🏍️', sales: '8.5万', tag: '热门' },
      ],
    },
    business: {
      listTitle: '物流服务',
      filters: ['全部', '国内快递', '国际物流', '大件物流', '冷链运输'],
      sortOptions: ['默认排序', '价格最低', '时效最快'],
      products: [
        {
          name: '标准快递',
          price: '¥12起',
          img: '📦',
          sales: '10万+',
          rating: 4.6,
          specs: ['1-3天', '3-5天'],
          colors: ['陆运', '空运'],
        },
        {
          name: '特快专递',
          price: '¥25起',
          img: '🚀',
          sales: '5.6万',
          rating: 4.8,
          specs: ['次日达'],
          colors: ['空运'],
        },
        {
          name: '冷链运输',
          price: '¥35起',
          img: '❄️',
          sales: '2.3万',
          rating: 4.7,
          specs: ['1-2天'],
          colors: ['冷藏', '冷冻'],
        },
        {
          name: '同城急送',
          price: '¥15起',
          img: '🏍️',
          sales: '8.5万',
          rating: 4.9,
          specs: ['2小时', '4小时'],
          colors: ['标准', '加急'],
        },
      ],
      detailProduct: {
        name: '标准快递',
        price: '¥12起',
        originalPrice: '¥15',
        sales: '10万+',
        rating: 4.6,
        description: '覆盖全国的标准快递服务，1-3天送达，支持在线追踪、电子签收。',
        features: ['全国覆盖', '在线追踪', '电子签收', '保价服务', '上门取件', '定时派送'],
        images: ['📦', '🚚', '📬'],
      },
    },
    personal: {
      userName: '张三',
      userAvatar: '👨',
      userLevel: '金卡会员',
      menus: [
        { label: '我的订单', icon: 'List', count: 8 },
        { label: '地址簿', icon: 'Location', count: 5 },
        { label: '我的收藏', icon: 'Star', count: 3 },
        { label: '帮助中心', icon: 'QuestionFilled', count: 0 },
      ],
      orders: [
        {
          id: 'WD20260101',
          product: '深圳→北京 标准快递',
          amount: '¥18',
          status: '运输中',
          date: '2026-01-20',
        },
        {
          id: 'WD20260102',
          product: '上海→成都 特快专递',
          amount: '¥32',
          status: '已签收',
          date: '2026-01-19',
        },
        {
          id: 'WD20260103',
          product: '广州→武汉 同城急送',
          amount: '¥15',
          status: '待取件',
          date: '2026-01-21',
        },
      ],
    },
  },

  hr: {
    name: '企务通',
    slogan: '高效办公，智慧协同',
    color: '#b195eb',
    industryKey: 'hr',
    home: {
      banners: [
        {
          title: '考勤打卡',
          subtitle: '一键打卡，准时出勤',
          bg: 'linear-gradient(135deg, #b195eb, #c4b5fd)',
        },
        {
          title: '待办事项',
          subtitle: '3项待办等待处理',
          bg: 'linear-gradient(135deg, #c4b5fd, #ddd6fe)',
        },
        {
          title: '公司公告',
          subtitle: '2026年春节放假通知',
          bg: 'linear-gradient(135deg, #ddd6fe, #ede9fe)',
        },
      ],
      categories: [
        { name: '考勤打卡', icon: '⏰' },
        { name: '请假申请', icon: '📝' },
        { name: '审批中心', icon: '✅' },
        { name: '通讯录', icon: '📇' },
        { name: '工资查询', icon: '💰' },
        { name: '报销申请', icon: '🧾' },
        { name: '培训学习', icon: '📚' },
        { name: '公告通知', icon: '📢' },
      ],
      hotProducts: [
        { name: '上班打卡', price: '', img: '⏰', sales: '1,234人已打卡', tag: '待办' },
        { name: '请假审批', price: '', img: '📋', sales: '2项待审批', tag: '待办' },
        { name: '工资条', price: '', img: '💰', sales: '1月工资已出', tag: '新' },
        { name: '培训报名', price: '', img: '📚', sales: 'Vue3技术培训', tag: '' },
        { name: '通讯录', price: '', img: '📇', sales: '1,234人', tag: '' },
        { name: '公司公告', price: '', img: '📢', sales: '3条新公告', tag: '新' },
      ],
    },
    business: {
      listTitle: '审批流程',
      filters: ['全部', '待我审批', '我发起的', '已审批'],
      sortOptions: ['默认排序', '紧急优先', '时间最新'],
      products: [
        {
          name: '请假申请 - 张三',
          price: '',
          img: '📋',
          sales: '3天年假',
          rating: 0,
          specs: ['待审批'],
          colors: ['普通'],
        },
        {
          name: '报销申请 - 李四',
          price: '',
          img: '🧾',
          sales: '¥3,500',
          rating: 0,
          specs: ['待审批'],
          colors: ['普通'],
        },
        {
          name: '出差申请 - 王五',
          price: '',
          img: '✈️',
          sales: '3天',
          rating: 0,
          specs: ['待审批'],
          colors: ['紧急'],
        },
        {
          name: '加班申请 - 赵六',
          price: '',
          img: '⏰',
          sales: '4小时',
          rating: 0,
          specs: ['已审批'],
          colors: ['普通'],
        },
      ],
      detailProduct: {
        name: '请假申请',
        price: '',
        originalPrice: '',
        sales: '',
        rating: 0,
        description: '在线提交请假申请，支持年假、病假、事假等多种类型，审批流程自动流转。',
        features: ['在线申请', '审批流转', '假期余额查询', '审批记录', '消息通知', '日历同步'],
        images: ['📋', '✅', '📅'],
      },
    },
    personal: {
      userName: '张三',
      userAvatar: '👨‍💻',
      userLevel: '高级工程师',
      menus: [
        { label: '我的考勤', icon: 'Clock', count: 0 },
        { label: '我的审批', icon: 'Stamp', count: 2 },
        { label: '个人信息', icon: 'User', count: 0 },
        { label: '工资条', icon: 'Money', count: 1 },
      ],
      orders: [
        { id: 'LA001', product: '年假申请 3天', amount: '', status: '已批准', date: '2026-01-25' },
        {
          id: 'LA002',
          product: '加班申请 4小时',
          amount: '',
          status: '待审批',
          date: '2026-01-22',
        },
        {
          id: 'RB001',
          product: '差旅报销 ¥3,500',
          amount: '',
          status: '已审批',
          date: '2026-01-18',
        },
      ],
    },
  },

  finance: {
    name: '财智通',
    slogan: '智能财务，高效管理',
    color: '#2f9999',
    industryKey: 'finance',
    home: {
      banners: [
        {
          title: '报销申请',
          subtitle: '在线提交，快速审批',
          bg: 'linear-gradient(135deg, #2f9999, #3cb8b8)',
        },
        {
          title: '工资查询',
          subtitle: '1月工资已出',
          bg: 'linear-gradient(135deg, #3cb8b8, #5cd4d4)',
        },
        {
          title: '预算申请',
          subtitle: 'Q1预算开放申请',
          bg: 'linear-gradient(135deg, #5cd4d4, #8ee0e0)',
        },
      ],
      categories: [
        { name: '报销申请', icon: '🧾' },
        { name: '工资查询', icon: '💰' },
        { name: '预算申请', icon: '📊' },
        { name: '发票管理', icon: '🧾' },
        { name: '借款申请', icon: '💳' },
        { name: '合同管理', icon: '📝' },
        { name: '税务服务', icon: '🏛️' },
        { name: '财务公告', icon: '📢' },
      ],
      hotProducts: [
        { name: '差旅报销', price: '', img: '✈️', sales: '快速提交', tag: '常用' },
        { name: '1月工资条', price: '', img: '💰', sales: '已出账', tag: '新' },
        { name: 'Q1预算申请', price: '', img: '📊', sales: '开放中', tag: '' },
        { name: '发票查验', price: '', img: '🧾', sales: '在线查验', tag: '' },
        { name: '借款申请', price: '', img: '💳', sales: '在线申请', tag: '' },
        { name: '财务公告', price: '', img: '📢', sales: '2条新公告', tag: '新' },
      ],
    },
    business: {
      listTitle: '报销申请',
      filters: ['全部', '差旅费', '办公用品', '招待费', '其他'],
      sortOptions: ['默认排序', '金额最大', '时间最新'],
      products: [
        {
          name: '差旅报销 - 北京出差',
          price: '¥3,500',
          img: '✈️',
          sales: '待审批',
          rating: 0,
          specs: ['差旅费'],
          colors: ['普通'],
        },
        {
          name: '办公用品采购',
          price: '¥1,200',
          img: '📦',
          sales: '待审批',
          rating: 0,
          specs: ['办公用品'],
          colors: ['普通'],
        },
        {
          name: '客户招待费',
          price: '¥5,600',
          img: '🍽️',
          sales: '待审批',
          rating: 0,
          specs: ['招待费'],
          colors: ['紧急'],
        },
        {
          name: '培训费用',
          price: '¥2,800',
          img: '📚',
          sales: '已审批',
          rating: 0,
          specs: ['培训费'],
          colors: ['普通'],
        },
      ],
      detailProduct: {
        name: '差旅报销',
        price: '¥3,500',
        originalPrice: '',
        sales: '',
        rating: 0,
        description: '在线提交差旅报销申请，上传凭证，自动审批流转，快速到账。',
        features: ['在线申请', '凭证上传', '审批流转', '进度查询', '快速到账', '电子发票'],
        images: ['✈️', '🧾', '💰'],
      },
    },
    personal: {
      userName: '张三',
      userAvatar: '👨‍💼',
      userLevel: '部门经理',
      menus: [
        { label: '我的报销', icon: 'Tickets', count: 3 },
        { label: '我的预算', icon: 'DataLine', count: 0 },
        { label: '个人信息', icon: 'User', count: 0 },
        { label: '发票管理', icon: 'Document', count: 12 },
      ],
      orders: [
        {
          id: 'RB001',
          product: '差旅报销',
          amount: '¥3,500',
          status: '待审批',
          date: '2026-01-20',
        },
        {
          id: 'RB002',
          product: '办公用品',
          amount: '¥1,200',
          status: '已审批',
          date: '2026-01-18',
        },
        { id: 'RB003', product: '招待费', amount: '¥5,600', status: '审批中', date: '2026-01-19' },
      ],
    },
  },

  restaurant: {
    name: '味享',
    slogan: '美味生活，尽在味享',
    color: '#ff9f40',
    industryKey: 'restaurant',
    home: {
      banners: [
        {
          title: '会员日特惠',
          subtitle: '全场菜品8折',
          bg: 'linear-gradient(135deg, #ff9f40, #ffbe76)',
        },
        {
          title: '新品上市',
          subtitle: '春季限定菜品',
          bg: 'linear-gradient(135deg, #ffbe76, #ffe0a6)',
        },
        {
          title: '积分兑换',
          subtitle: '100积分抵1元',
          bg: 'linear-gradient(135deg, #ffe0a6, #fff3d6)',
        },
      ],
      categories: [
        { name: '招牌菜', icon: '🍳' },
        { name: '主食', icon: '🍚' },
        { name: '小吃', icon: '🥟' },
        { name: '饮品', icon: '🧋' },
        { name: '甜品', icon: '🍰' },
        { name: '套餐', icon: '🍱' },
        { name: '会员专区', icon: '👑' },
        { name: '活动专区', icon: '🎉' },
      ],
      hotProducts: [
        {
          name: '宫保鸡丁套餐',
          price: '¥38',
          originalPrice: '¥48',
          img: '🍗',
          sales: '5,600',
          tag: '招牌',
        },
        {
          name: '红烧肉套餐',
          price: '¥42',
          originalPrice: '¥52',
          img: '🥩',
          sales: '3,200',
          tag: '',
        },
        {
          name: '清蒸鲈鱼',
          price: '¥68',
          originalPrice: '¥88',
          img: '🐟',
          sales: '2,800',
          tag: '新品',
        },
        {
          name: '麻婆豆腐',
          price: '¥28',
          originalPrice: '¥35',
          img: '🫘',
          sales: '4,100',
          tag: '',
        },
        {
          name: '酸菜鱼',
          price: '¥58',
          originalPrice: '¥68',
          img: '🐠',
          sales: '3,900',
          tag: '热卖',
        },
        { name: '蛋炒饭', price: '¥18', originalPrice: '¥22', img: '🍚', sales: '6,200', tag: '' },
      ],
    },
    business: {
      listTitle: '菜品列表',
      filters: ['全部', '招牌菜', '主食', '小吃', '饮品', '套餐'],
      sortOptions: ['默认排序', '价格从低到高', '销量优先'],
      products: [
        {
          name: '宫保鸡丁套餐',
          price: '¥38',
          img: '🍗',
          sales: '5,600',
          rating: 4.8,
          specs: ['大份', '小份'],
          colors: ['微辣', '中辣', '特辣'],
        },
        {
          name: '红烧肉套餐',
          price: '¥42',
          img: '🥩',
          sales: '3,200',
          rating: 4.7,
          specs: ['大份', '小份'],
          colors: ['标准'],
        },
        {
          name: '清蒸鲈鱼',
          price: '¥68',
          img: '🐟',
          sales: '2,800',
          rating: 4.9,
          specs: ['整条'],
          colors: ['清蒸', '红烧'],
        },
        {
          name: '酸菜鱼',
          price: '¥58',
          img: '🐠',
          sales: '3,900',
          rating: 4.8,
          specs: ['大份', '小份'],
          colors: ['微辣', '中辣'],
        },
      ],
      detailProduct: {
        name: '宫保鸡丁套餐',
        price: '¥38',
        originalPrice: '¥48',
        sales: '5,600',
        rating: 4.8,
        description: '精选鸡胸肉，配以花生米、干辣椒爆炒，麻辣鲜香，搭配米饭和时蔬。',
        features: ['精选食材', '现炒现做', '搭配米饭', '时蔬配菜', '免费加饭', '会员折扣'],
        images: ['🍗', '🍱', '🍚'],
      },
    },
    personal: {
      userName: '张先生',
      userAvatar: '👨',
      userLevel: '金卡会员',
      menus: [
        { label: '我的积分', icon: 'Coin', count: 5600 },
        { label: '消费记录', icon: 'List', count: 45 },
        { label: '优惠券', icon: 'Ticket', count: 3 },
        { label: '个人信息', icon: 'User', count: 0 },
      ],
      orders: [
        {
          id: 'OD20260101',
          product: '宫保鸡丁套餐',
          amount: '¥38',
          status: '已完成',
          date: '2026-01-20',
        },
        {
          id: 'OD20260102',
          product: '清蒸鲈鱼',
          amount: '¥68',
          status: '已完成',
          date: '2026-01-19',
        },
        {
          id: 'OD20260103',
          product: '酸菜鱼套餐',
          amount: '¥58',
          status: '待取餐',
          date: '2026-01-21',
        },
      ],
    },
  },

  community: {
    name: '邻里通',
    slogan: '智慧社区，美好家园',
    color: '#00b42a',
    industryKey: 'community',
    home: {
      banners: [
        {
          title: '社区公告',
          subtitle: '春节放假通知',
          bg: 'linear-gradient(135deg, #00b42a, #23d160)',
        },
        {
          title: '在线报修',
          subtitle: '一键报修，快速响应',
          bg: 'linear-gradient(135deg, #23d160, #48d88a)',
        },
        {
          title: '活动报名',
          subtitle: '社区春晚报名中',
          bg: 'linear-gradient(135deg, #48d88a, #6ee7a0)',
        },
      ],
      categories: [
        { name: '在线报修', icon: '🔧' },
        { name: '物业缴费', icon: '💰' },
        { name: '活动报名', icon: '🎉' },
        { name: '投诉建议', icon: '💬' },
        { name: '访客邀请', icon: '👋' },
        { name: '车位预约', icon: '🅿️' },
        { name: '快递代收', icon: '📦' },
        { name: '社区服务', icon: '🤝' },
      ],
      hotProducts: [
        { name: '水电报修', price: '', img: '🔧', sales: '快速响应', tag: '常用' },
        { name: '物业费缴纳', price: '', img: '💰', sales: '在线缴费', tag: '' },
        { name: '社区春晚', price: '', img: '🎉', sales: '报名中', tag: '热门' },
        { name: '电梯维修', price: '', img: '🏗️', sales: '已处理', tag: '' },
        { name: '快递代收', price: '', img: '📦', sales: '2件待取', tag: '新' },
        { name: '车位预约', price: '', img: '🅿️', sales: '剩余5位', tag: '' },
      ],
    },
    business: {
      listTitle: '社区服务',
      filters: ['全部', '报修服务', '活动报名', '投诉建议', '便民服务'],
      sortOptions: ['默认排序', '最新发布', '紧急优先'],
      products: [
        {
          name: '水电报修',
          price: '',
          img: '🔧',
          sales: '24h响应',
          rating: 4.6,
          specs: ['紧急', '普通'],
          colors: ['水电', '门窗', '电梯'],
        },
        {
          name: '社区春晚报名',
          price: '',
          img: '🎉',
          sales: '限50人',
          rating: 0,
          specs: ['1月28日'],
          colors: ['表演', '观众'],
        },
        {
          name: '投诉建议',
          price: '',
          img: '💬',
          sales: '在线提交',
          rating: 0,
          specs: ['24h回复'],
          colors: ['投诉', '建议'],
        },
        {
          name: '访客邀请',
          price: '',
          img: '👋',
          sales: '在线邀请',
          rating: 0,
          specs: ['即时生效'],
          colors: ['临时', '长期'],
        },
      ],
      detailProduct: {
        name: '在线报修',
        price: '',
        originalPrice: '',
        sales: '',
        rating: 4.6,
        description: '在线提交报修申请，上传问题描述和图片，物业快速响应处理。',
        features: ['在线提交', '图片上传', '进度追踪', '维修评价', '紧急通道', '历史记录'],
        images: ['🔧', '🏠', '✅'],
      },
    },
    personal: {
      userName: '张先生',
      userAvatar: '👨',
      userLevel: '1栋101',
      menus: [
        { label: '我的报修', icon: 'SetUp', count: 1 },
        { label: '我的活动', icon: 'Calendar', count: 2 },
        { label: '住户信息', icon: 'House', count: 0 },
        { label: '投诉建议', icon: 'ChatDotRound', count: 0 },
      ],
      orders: [
        {
          id: 'RP001',
          product: '厨房水龙头漏水',
          amount: '',
          status: '处理中',
          date: '2026-01-20',
        },
        {
          id: 'RP002',
          product: '卧室窗户关不严',
          amount: '',
          status: '待处理',
          date: '2026-01-21',
        },
        { id: 'RP003', product: '电梯异响', amount: '', status: '已处理', date: '2026-01-19' },
      ],
    },
  },

  project: {
    name: '协作云',
    slogan: '高效协作，项目无忧',
    color: '#13c2c2',
    industryKey: 'project',
    home: {
      banners: [
        {
          title: '项目看板',
          subtitle: '4个项目进行中',
          bg: 'linear-gradient(135deg, #13c2c2, #36cfc9)',
        },
        {
          title: '待办任务',
          subtitle: '6项任务待处理',
          bg: 'linear-gradient(135deg, #36cfc9, #5cdbd3)',
        },
        {
          title: '团队公告',
          subtitle: 'Q1目标已发布',
          bg: 'linear-gradient(135deg, #5cdbd3, #87e8de)',
        },
      ],
      categories: [
        { name: '任务看板', icon: '📋' },
        { name: '项目列表', icon: '📁' },
        { name: '文档中心', icon: '📄' },
        { name: '团队通讯', icon: '💬' },
        { name: '日程安排', icon: '📅' },
        { name: '文件共享', icon: '📂' },
        { name: '会议管理', icon: '🎥' },
        { name: '数据报表', icon: '📊' },
      ],
      hotProducts: [
        { name: '电商平台项目', price: '', img: '🛒', sales: '进度78%', tag: '进行中' },
        { name: '教育系统项目', price: '', img: '📚', sales: '进度45%', tag: '进行中' },
        { name: '前端页面开发', price: '', img: '💻', sales: '截止2/1', tag: '紧急' },
        { name: 'API接口联调', price: '', img: '⚙️', sales: '截止2/15', tag: '' },
        { name: 'UI设计评审', price: '', img: '🎨', sales: '截止2/10', tag: '' },
        { name: '数据库设计', price: '', img: '🗄️', sales: '已完成', tag: '完成' },
      ],
    },
    business: {
      listTitle: '项目详情',
      filters: ['全部', '进行中', '待开始', '已完成', '已暂停'],
      sortOptions: ['默认排序', '截止日期', '优先级'],
      products: [
        {
          name: '电商平台 - 前端开发',
          price: '',
          img: '💻',
          sales: '进行中',
          rating: 0,
          specs: ['高优先级'],
          colors: ['张三'],
        },
        {
          name: '电商平台 - API联调',
          price: '',
          img: '⚙️',
          sales: '待开始',
          rating: 0,
          specs: ['中优先级'],
          colors: ['李四'],
        },
        {
          name: '教育系统 - 测试用例',
          price: '',
          img: '🧪',
          sales: '待开始',
          rating: 0,
          specs: ['中优先级'],
          colors: ['钱七'],
        },
        {
          name: '电商平台 - 数据库设计',
          price: '',
          img: '🗄️',
          sales: '已完成',
          rating: 0,
          specs: ['高优先级'],
          colors: ['王五'],
        },
      ],
      detailProduct: {
        name: '电商平台项目',
        price: '',
        originalPrice: '',
        sales: '进度78%',
        rating: 0,
        description: '电商平台全栈开发项目，包含前端页面、后端API、数据库设计等模块。',
        features: ['任务看板', '进度跟踪', '成员管理', '文档协作', '代码审查', '风险预警'],
        images: ['📋', '📊', '👥'],
      },
    },
    personal: {
      userName: '张三',
      userAvatar: '👨‍💻',
      userLevel: '前端工程师',
      menus: [
        { label: '我的任务', icon: 'List', count: 6 },
        { label: '我的项目', icon: 'FolderOpened', count: 3 },
        { label: '个人信息', icon: 'User', count: 0 },
        { label: '消息通知', icon: 'Bell', count: 5 },
      ],
      orders: [
        { id: 'TSK001', product: '前端页面开发', amount: '', status: '进行中', date: '2026-02-01' },
        { id: 'TSK002', product: 'API接口联调', amount: '', status: '待开始', date: '2026-02-15' },
        { id: 'TSK003', product: '数据库设计', amount: '', status: '已完成', date: '2026-01-25' },
      ],
    },
  },
};

export default userPortalConfigs;
